Repository jack0928/SE-Term-Project-2025, pull requests merged in 2025-05, with the labels that each got.

#2 Feature/add template
  .github/ISSUE_TEMPLATE/feature-request.md
  .github/PULL_REQUEST_TEMPLATE.md
  .gradle/8.10/checksums/checksums.lock
  .gradle/8.10/checksums/md5-checksums.bin
  .gradle/8.10/checksums/sha1-checksums.bin
  .gradle/8.10/dependencies-accessors/gc.properties
  .gradle/8.10/executionHistory/executionHistory.lock
  .gradle/8.10/fileChanges/last-build.bin
  .gradle/8.10/fileHashes/fileHashes.lock
  .gradle/8.10/gc.properties
  .gradle/buildOutputCleanup/buildOutputCleanup.lock
  .gradle/buildOutputCleanup/cache.properties
  .gradle/vcs-1/gc.properties
  .idea/workspace.xml
Labels: docs, 진하

#1 feat: 프로젝트 초기구조 및 기본클래스 추가
  .gitignore
  .idea/.gitignore
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
  src/main/java/com/yutnori/YutnoriApplication.java
  src/main/java/com/yutnori/controller/GameController.java
  src/main/java/com/yutnori/controller/PieceMoveController.java
  src/main/java/com/yutnori/controller/YutController.java
  src/main/java/com/yutnori/model/Board.java
  src/main/java/com/yutnori/model/Cell.java
  src/main/java/com/yutnori/model/Game.java
  src/main/java/com/yutnori/model/HexagonBoard.java
  src/main/java/com/yutnori/model/PentagonBoard.java
  src/main/java/com/yutnori/model/Piece.java
  src/main/java/com/yutnori/model/Player.java
  src/main/java/com/yutnori/model/SquareBoard.java
  src/main/java/com/yutnori/model/Yut.java
  src/main/java/com/yutnori/view/BoardView.java
  src/main/java/com/yutnori/view/GameView.java
  src/main/java/com/yutnori/view/PlayerStatusView.java
  src/main/java/com/yutnori/view/YutResultView.java
Labels: feat, 진하

#8 Feat: 윷 기능, UI 및 controller 구현
  src/main/java/com/yutnori/controller/YutController.java
  src/main/java/com/yutnori/model/Yut.java
  src/main/java/com/yutnori/view/TestYutView.java
  src/main/java/com/yutnori/view/YutResultView.java
Labels: feat, 정우

#9 feat: added Piece UI. It now appears on the board and moves around by…
  src/main/java/com/yutnori/controller/PieceMoveController.java
  src/main/java/com/yutnori/model/Board.java
  src/main/java/com/yutnori/model/HexagonBoard.java
  src/main/java/com/yutnori/model/PentagonBoard.java
  src/main/java/com/yutnori/model/Piece.java
  src/main/java/com/yutnori/model/Player.java
  src/main/java/com/yutnori/model/SquareBoard.java
  src/main/java/com/yutnori/view/BoardView.java
  src/main/java/com/yutnori/view/TestPieceView.java
  src/main/java/com/yutnori/view/TestSqaureBoardView.java
Labels: feat, 민규

#13 feat: PlayerStatusView 구현
  src/main/java/com/yutnori/view/PlayerStatusView.java
Labels: feat, 정우

#16 fix: fixed MVC Structure of board class and TestPieceView. Also, usel…
  .idea/.name
  src/main/java/com/yutnori/controller/PieceMoveController.java
  src/main/java/com/yutnori/model/Board.java
  src/main/java/com/yutnori/model/Cell.java
  src/main/java/com/yutnori/model/HexagonBoard.java
  src/main/java/com/yutnori/model/PentagonBoard.java
  src/main/java/com/yutnori/model/Piece.java
  src/main/java/com/yutnori/model/SquareBoard.java
  src/main/java/com/yutnori/view/BoardView.java
  src/main/java/com/yutnori/view/TestHexaBoardView.java
  src/main/java/com/yutnori/view/TestPentaBoardView.java
  src/main/java/com/yutnori/view/TestPieceView.java
  src/main/java/com/yutnori/view/TestSqaureBoardView.java
  src/main/java/com/yutnori/view/YutResultView.java
Labels: fix, 민규

#19 fix: throwRandomYut을 확률에 따라 던지게 수정
  src/main/java/com/yutnori/model/Yut.java
Labels: fix, 정우

#20 Fix: movement logic repair - 1
  src/main/java/com/yutnori/controller/PieceMoveController.java
  src/main/java/com/yutnori/model/Board.java
  src/main/java/com/yutnori/model/Cell.java
  src/main/java/com/yutnori/model/HexagonBoard.java
  src/main/java/com/yutnori/model/PentagonBoard.java
  src/main/java/com/yutnori/model/Piece.java
  src/main/java/com/yutnori/model/SquareBoard.java
Labels: fix, 진하

#21 Feature/integrated UI
  .idea/gradle.xml
  .idea/misc.xml
  src/main/java/com/yutnori/controller/PieceMoveController.java
  src/main/java/com/yutnori/model/Cell.java
  src/main/java/com/yutnori/model/Piece.java
  src/main/java/com/yutnori/model/SquareBoard.java
  src/main/java/com/yutnori/view/BoardView.java
  src/main/java/com/yutnori/view/TestPieceView.java
Labels: fix, 민규

#23 Fix: fixed movement loggic add
  .idea/gradle.xml
  src/main/java/com/yutnori/controller/PieceMoveController.java
  src/main/java/com/yutnori/model/Board.java
  src/main/java/com/yutnori/model/Cell.java
  src/main/java/com/yutnori/model/HexagonBoard.java
  src/main/java/com/yutnori/model/PentagonBoard.java
  src/main/java/com/yutnori/model/Piece.java
  src/main/java/com/yutnori/model/SquareBoard.java
  src/main/java/com/yutnori/model/Yut.java
Labels: fix, 진하

#24 fix:선택 윷 던지기와 랜덤 윷 던지기 버튼 추가, 선택 윷 던지기의 값 선택을 위한 드롭다운 추가,YutControlle…
  src/main/java/com/yutnori/controller/YutController.java
  src/main/java/com/yutnori/view/TestYutView.java
  src/main/java/com/yutnori/view/YutResultView.java
Labels: fix, 정우

#26 Fix: YutController 수정
  src/main/java/com/yutnori/controller/YutController.java
Labels: fix, 정우

#28 Feat: added total UI and options for users
  src/main/java/com/yutnori/controller/PieceMoveController.java
  src/main/java/com/yutnori/controller/YutController.java
  src/main/java/com/yutnori/model/Piece.java
  src/main/java/com/yutnori/model/SquareBoard.java
  src/main/java/com/yutnori/view/PlayerStatusView.java
  src/main/java/com/yutnori/view/TestPieceView.java
Labels: feat, 민규

#29 Feature/add grouping
  src/main/java/com/yutnori/controller/PieceMoveController.java
  src/main/java/com/yutnori/model/Cell.java
  src/main/java/com/yutnori/model/HexagonBoard.java
  src/main/java/com/yutnori/model/PentagonBoard.java
  src/main/java/com/yutnori/model/Piece.java
  src/main/java/com/yutnori/model/SquareBoard.java
  src/main/java/com/yutnori/view/TestPieceView.java
Labels: feat, 진하

#32 [Feat] 승리, 재시작, 게임 종료 기능 구현
  src/main/java/com/yutnori/YutnoriApplication.java
  src/main/java/com/yutnori/controller/GameController.java
  src/main/java/com/yutnori/controller/PieceMoveController.java
  src/main/java/com/yutnori/controller/YutController.java
  src/main/java/com/yutnori/model/Board.java
  src/main/java/com/yutnori/model/Cell.java
  src/main/java/com/yutnori/model/Game.java
  src/main/java/com/yutnori/model/Piece.java
  src/main/java/com/yutnori/model/Player.java
  src/main/java/com/yutnori/model/Yut.java
  src/main/java/com/yutnori/view/BoardView.java
  src/main/java/com/yutnori/view/GameView.java
  src/main/java/com/yutnori/view/PlayerStatusView.java
  src/main/java/com/yutnori/view/TestHexaBoardView.java
  src/main/java/com/yutnori/view/TestPentaBoardView.java
  src/main/java/com/yutnori/view/TestPieceView.java
  src/main/java/com/yutnori/view/TestSqaureBoardView.java
  src/main/java/com/yutnori/view/TestYutView.java
Labels: feat, 민규

#38 [Fix] 빽도 상황 정리 및 main() refactoring
  src/main/java/com/yutnori/YutnoriApplication.java
  src/main/java/com/yutnori/controller/GameController.java
  src/main/java/com/yutnori/model/PentagonBoard.java
  src/main/java/com/yutnori/model/SquareBoard.java
  src/main/java/com/yutnori/view/GameView.java
Labels: fix, 민규

#40 [Fix]: Grouping's Grouping Issue fixed
  src/main/java/com/yutnori/controller/PieceMoveController.java
  src/main/java/com/yutnori/model/Piece.java
Labels: fix, 민규

#41 [Feat] 업은 말에 대한 정보 표시
  src/main/java/com/yutnori/YutnoriApplication.java
  src/main/java/com/yutnori/controller/GameController.java
  src/main/java/com/yutnori/controller/PieceMoveController.java
  src/main/java/com/yutnori/model/Piece.java
  src/main/java/com/yutnori/view/GameView.java
Labels: feat, 민규

#44 [Fix] 빽도 관련 issue resolve (빽도 악용 방지)
  src/main/java/com/yutnori/controller/PieceMoveController.java
  src/main/java/com/yutnori/model/Piece.java
Labels: fix, 민규

#45 [Fix] fixed finishing logic
  src/main/java/com/yutnori/controller/PieceMoveController.java
  src/main/java/com/yutnori/model/Piece.java
Labels: fix, 민규

#47 [Fix] 빽도 문제 수정 및 노드 ID 숫자 제거
  src/main/java/com/yutnori/controller/GameController.java
  src/main/java/com/yutnori/model/Cell.java
  src/main/java/com/yutnori/model/SquareBoard.java
  src/main/java/com/yutnori/view/BoardView.java
  src/main/java/com/yutnori/view/GameView.java
Labels: fix, 민규

#49 [Fix] grouping in center error
  src/main/java/com/yutnori/controller/GameController.java
  src/main/java/com/yutnori/controller/PieceMoveController.java
  src/main/java/com/yutnori/view/BoardView.java
Labels: fix, 진하

#50 [Fix] UI and 빽도 fixation
  src/main/java/com/yutnori/controller/PieceMoveController.java
  src/main/java/com/yutnori/view/BoardView.java
  src/main/java/com/yutnori/view/GameView.java
Labels: fix, 민규

#51 [Fix] SquareBoard Exception Handling
  src/main/java/com/yutnori/controller/PieceMoveController.java
  src/main/java/com/yutnori/view/BoardView.java
Labels: fix, 민규

#52 [Fix] finish and grouping/capturing order modified
  src/main/java/com/yutnori/controller/PieceMoveController.java
Labels: fix, 민규

#53 Test/update capture condition
  .idea/artifacts/SE_2025_Yutnori_jar.xml
  META-INF/MANIFEST.MF
  src/main/java/com/yutnori/controller/GameController.java
  src/main/java/com/yutnori/controller/PieceMoveController.java
  src/test/java/com/yutnori/controller/PieceMoveControllerTest.java
Labels: test, 진하

#54 fix: grouping's grouping error 2
  src/main/java/com/yutnori/view/BoardView.java
Labels: fix, 진하

#56 Feat: JavaFX 버전 YutResultView 제작
  .gitignore
  build.gradle
  src/main/java/com/yutnori/FXview/FXYutResultView.java
  src/main/java/com/yutnori/FXview/FXYutTest.java
Labels: feat, 정우

#58 [Feat] FXBoardView (BoardView but in JavaFX instead of Swing)
  .idea/artifacts/SE_2025_Yutnori_jar.xml
  .idea/artifacts/SE_2025_Yutnori_main_jar.xml
  src/main/java/com/yutnori/FXview/FXBoardView.java
  src/main/java/com/yutnori/FXview/FXGameView.java
  src/main/java/com/yutnori/FXview/FXPlayerStatusView.java
  src/main/java/com/yutnori/FXview/TestFXHexaBoardView.java
  src/main/java/com/yutnori/FXview/TestFXPentaBoardView.java
  src/main/java/com/yutnori/FXview/TestFXSquareBoardView.java
  src/main/java/com/yutnori/controller/GameController.java
  src/main/java/com/yutnori/controller/PieceMoveController.java
Labels: feat, 민규

#60 feat: FXPlayerStatusView 생성, TestFXPlayerStatusView로 테스트 가능
  build.gradle
  src/main/java/com/yutnori/FXview/FXPlayerStatusView.java
  src/main/java/com/yutnori/FXview/TestFXPlayerStatusView.java
Labels: feat, 정우

#63 [Feat] GameView 및 View 관련 MVC 구조 개선
  src/main/java/com/yutnori/FXview/FXBoardView.java
  src/main/java/com/yutnori/FXview/FXGameView.java
  src/main/java/com/yutnori/FXview/FXPlayerStatusView.java
  src/main/java/com/yutnori/FXview/FXYutResultView.java
  src/main/java/com/yutnori/FXview/FXYutTest.java
  src/main/java/com/yutnori/FXview/TestFXHexaBoardView.java
  src/main/java/com/yutnori/FXview/TestFXPentaBoardView.java
  src/main/java/com/yutnori/FXview/TestFXPlayerStatusView.java
  src/main/java/com/yutnori/FXview/TestFXSquareBoardView.java
  src/main/java/com/yutnori/YutnoriApplication.java
  src/main/java/com/yutnori/YutnoriFXApplication.java
  src/main/java/com/yutnori/controller/GameController.java
  src/main/java/com/yutnori/controller/YutController.java
  src/main/java/com/yutnori/view/BoardView.java
  src/main/java/com/yutnori/view/GameView.java
  src/main/java/com/yutnori/view/PlayerStatusView.java
  src/main/java/com/yutnori/view/YutResultView.java
  src/main/java/com/yutnori/viewInterface/BoardViewInterface.java
  src/main/java/com/yutnori/viewInterface/GameViewInterface.java
  src/main/java/com/yutnori/viewInterface/PlayerStatusViewInterface.java
  src/main/java/com/yutnori/viewInterface/YutResultViewInterface.java
Labels: feat, fix, 민규

#65 Test/refactor based on new structure
  src/test/java/com/yutnori/controller/GameControllerTest.java
Labels: test, 재민
